name: Auto Assignee assignment

on:
  issues:
    types: [ opened ]
  pull_request_target:
    types: [ opened, ready_for_review, converted_to_draft ]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Auto-assign issue'
        uses: pozil/auto-assign-issue@v1.11.0
        with:
          assignees: ${{github.actor}}
          numOfAssignee: 1
          allowSelfAssign: true
          removePreviousAssignees: true
